Go based archiving of .pkg creation
go-pkg-org/gopkg pull request #20
Opened 2020-10-17 14:04 UTC by Johannestegner

The build command now makes use of a `archive` file which contains a function to create a set of file-mappings between a real file (on the file system) and a path inside a tar file (which is not yet created). It also contains a function to use the resulting slice and create a gzipped tar file with .pkg file type.

2020-10-17 18:10 UTC, creekorful requested changes
First of all thanks for the PR! The tar refactoring is really nice.

I've got some comments / suggestions.

2020-10-17 18:10 UTC, creekorful commented on internal/build/build.go
> +	if err := CreateTar(filepath.Join("build", pkgName), dir, true); err != nil {
archive.Create then

2020-10-17 18:10 UTC, creekorful commented on internal/build/build.go
> +		log.Panicf("failed to build archive: %s", err)
wrong package I think. Should be zerolog/log package. No?
btw while not simply `return err`?

2020-10-17 18:53 UTC, Johannestegner commented on internal/build/archive.go
> +package build
Aye, I put it there from start, then I thought that due to it only being used by the build script for now, it would be better to keep it close to it and then refactor it when we want it for another part!
So I totally get your thought (and I had it too), but due to it being specific at the current code, I think it fits better in that package!

(Also very open for it not to be, so if you feel strong for it I will move it :P )

2020-10-17 18:56 UTC, Johannestegner commented on .gitignore
> +vendor
Hah, I sometimes vendor download packages for some of my machines, just to keep the go-root clean (different disks), I do that on my laptop, and added it just to make sure I did not accidentally add it later on :P

2020-10-17 18:58 UTC, Johannestegner commented on internal/build/archive.go
> +		fileTypes = append(fileTypes, "all")
Aye, you are right. I'm quite novice with go, the last few years I've worked a lot with PHP where `count(..)` is quite expensive. Go is compiled, so ofc using that is a better way :)

2020-10-17 18:59 UTC, Johannestegner commented on internal/build/build.go
> +		log.Panicf("failed to build archive: %s", err)
I think I just missed that one, hehe. Will fix ;)

2020-10-17 20:58 UTC, creekorful commented on internal/build/archive.go
> +package build
I will certainly need to access / parse the .pkg file for the `install` `remove` command implementation, so moving it to a dedicated archive package make sense to me 👍🏻

2020-10-18 08:21 UTC, Johannestegner commented on internal/build/build.go
> +	fmt.Printf("Successfully build %s\n", pkgName)
It should probably not be a `fmt.Printf`, but possibly an info message, I would make it a bit more than debug as we probably want to show that to the user, right? :)

2020-10-18 08:28 UTC, creekorful commented on internal/build/build.go
> +	fmt.Printf("Successfully build %s\n", pkgName)
Totally right!

Can you do something like this?

```
log.Info().Str("package", pkgName).Msg("Building source package")
```

2020-10-18 08:36 UTC, Johannestegner commented on internal/build/archive.go
> +		if strings.Index(file.Name(), ".") == 0 {
I thought about that too, had some issues with the git directory being added (which I find kinda wrong) and am a bit scared that stuff like .env would be added too.
Maybe we should use some sort of .gopkgignore file?

2020-10-18 08:36 UTC, Johannestegner commented on internal/build/archive.go
> +		if _, err := ioutil.ReadFile(path); err != nil {
Ah, I missed that method, good call!

2020-10-18 09:41 UTC, creekorful requested changes

2020-10-18 09:41 UTC, creekorful commented on internal/build/build.go
> +	log.Info().Str("package", pkg.Package).Msg("Successfully built package")
Successfully built binary package?

2020-10-18 09:41 UTC, creekorful commented on internal/build/build.go
> +	log.Info().Str("package", pkg.Package).Msg("Successfully built package")
Successfully built source package?

2020-10-18 09:41 UTC, creekorful commented on internal/build/build.go
> +		log.Info().Str("package", pkg.Package).Msg("Building source package")
you can remove this one since logging is done inside buildXXX methods

2020-10-18 09:41 UTC, creekorful commented on internal/archive/archive_test.go
> +	dir, _ := ioutil.TempDir("", "*")
pattern should be gopkg, no?

2020-10-18 09:41 UTC, creekorful commented on internal/archive/archive_test.go
> +	jsonFile, _ := ioutil.TempFile(dir, "*.json")
same comment as above

2020-10-18 09:45 UTC, Johannestegner commented on internal/archive/archive_test.go
> +	dir, _ := ioutil.TempDir("", "*")
I started with using `gopkg` as the dir name, but the `Temp*()` method appends a random number on each of the files, so when using `gopkg.json` for example, we get `gopkg.json43879344` and similar, which kinda messes up the functionality! hehe

In the current case it creates a directory with random numbers, then creates files which looks like `345345.json` etc.

2020-10-18 09:50 UTC, creekorful commented on internal/archive/archive_test.go
> +	dir, _ := ioutil.TempDir("", "*")
Didn't know that, thanks!

2020-10-18 10:14 UTC, creekorful commented on internal/archive/archive.go
> +			if file.Name() == ".git" || file.Name() == control.GoPkgDir {
One last thing (the last :p)
Can you add a // TODO with the Github issue?

2020-10-18 10:19 UTC, creekorful approved these changes

2020-10-18 10:19 UTC, merged