Add config package with support for file and env variables
go-pkg-org/gopkg pull request #41
Opened 2020-10-20 15:02 UTC by frozzare

This is a draft of #34 

It's quite simple, you create a default config and runs the load method to load from yml/yaml files, then looks if there are any environment variables to load from after.

Example

```
GOPKG_BIN_DIR=path/to/bin
```

```yml
maintainer:
  email: test@example.com
```

```go
c := &config.Config{
	Maintainer: config.Maintainer{
		Name: "Test",
	},
}

if err := c.Load(); err != nil {
	log.Error(err);
}

fmt.Println(c)
```

```
c.Maintainer.Name = Test
c.Maintainer.Email = test@example.com
c.BinDir = path/to/dir
```

2020-10-22 21:12 UTC, creekorful requested changes
Thanks for the PR! it will be really helpful 👍🏻 

I have some comments / bike-shedding.

2020-10-22 21:12 UTC, creekorful commented on internal/config/config.go
> +func (c *Config) Load() error {
I dont think this method should be exposed, is there a reason?

2020-10-22 21:12 UTC, creekorful commented on internal/util/file/file_test.go
> +func tempFileName(prefix, suffix string) string {
ioutil.TempFile ? 
https://golang.org/pkg/io/ioutil/#TempFile

2020-10-22 21:12 UTC, creekorful commented on internal/util/file/file_test.go
> +		if runtime.GOOS != "windows" {
wut?

2020-10-22 21:12 UTC, creekorful commented on internal/util/file/file.go
> +	errNoFileFound = errors.New("No file found")
I think you should make this public, no reason to create a custom error type otherwise?

2020-10-22 21:12 UTC, creekorful commented on internal/config/config.go
> +	Email string `yaml:"email"`
no more configurable trough env variable or I am missing something?

2020-10-23 06:30 UTC, frozzare commented on internal/config/config.go
> +func (c *Config) Load() error {
Not really after creating the `Default` method.

2020-10-23 06:31 UTC, frozzare commented on internal/util/file/file_test.go
> +		if runtime.GOOS != "windows" {
Yep, windows can't delete the files when the test is finished. I'm no windows expert so can't fix that.

2020-10-23 06:31 UTC, frozzare commented on internal/util/file/file.go
> +	errNoFileFound = errors.New("No file found")
Ah, yeah you're right.

2020-10-23 06:32 UTC, frozzare commented on internal/config/config.go
> +	Email string `yaml:"email"`
It is, `GOPKG_MAINTAINER_EMAIL`, you don't need to specific it. But I can specific it to be clear.

2020-10-23 06:32 UTC, frozzare commented on internal/util/file/file_test.go
> +func tempFileName(prefix, suffix string) string {
Ah, didn't know that existed.

2020-10-23 06:41 UTC, frozzare commented on internal/util/file/file_test.go
> +func tempFileName(prefix, suffix string) string {
Hm, `ioutil.TempFile` don't create the same paths that I want, so skipping it. 

with `ioutil.TempFile`
```
/var/folders/_p/lny16j2j133g_6bfcjg07wxd_tfqr4/T/.gopkg1.yaml939142247
```

with `tempFileName`
```
/var/folders/_p/lny16j2j133g_6bfcjg07wxd_tfqr4/T/.11779ebd47a3bda4bedf829a59696cbe.yaml
```

2020-10-23 06:42 UTC, frozzare commented on internal/util/file/file_test.go
> +		if runtime.GOOS != "windows" {
Maybe @Johannestegner can look into this later.

2020-10-23 07:41 UTC, creekorful approved these changes

2020-10-23 08:39 UTC, Johannestegner approved these changes
LGTM!

2020-10-23 08:39 UTC, merged