Fix issue with go test when no go files exists
go-pkg-org/gopkg pull request #53
Opened 2020-10-23 14:27 UTC by frozzare

This solves #52 

If no packages/go files exists it won't display error output from go test

```
→ gopkg build github.com-frozzare-gopkg-nongo
2:41PM INF Building for control package importPath=github.com/frozzare/gopkg-nongo version=0.0~git202010221942-1
2:41PM ERR No go packages found
```

2020-10-23 22:42 UTC, creekorful requested changes

2020-10-23 22:42 UTC, creekorful commented on internal/build/build.go
> +	if len(output) == 0 {
I guess that's the same thing as doing:

```go
if err := cmd.Run(); err != nil {
   log.Error().Msg("No go packages found")
   return nil
}
```

You are getting len(output) == 0 because nothing goes into stdout since the command execution fails.

So if we are assuming that `go test ./...` will only fails if there's no packages in directory, I will keep the old `cmd.Run()` stuff, and add the logging "no Go files found" instead of returning the error.

What do you think?

2020-10-24 10:19 UTC, frozzare commented on internal/build/build.go
> +	if len(output) == 0 {
Hm, no it's not the same thing. 

If you do it like this

```go
if err := cmd.Run(); err != nil {
   log.Error().Msg("No go packages found")
   return nil
}
```

It will work fine when you don't have any go files in the folder, but when you do you log the `no go packages found` message even if you get output from `go test ./...`

```
12:16PM INF Building for control package importPath=github.com/frozzare/gopkg-nongo version=0.0~git202010221942-1
--- FAIL: TestMain (0.00s)
    main_test.go:6: Err
FAIL
FAIL	_/Users/fredrik/u/go/src/github.com/frozzare/gopkg-nongo/github.com-frozzare-gopkg-nongo	0.063s
FAIL
12:16PM ERR No go packages found
```

So with `len(output) == 0` you can tell that `go test ./...` don't give any output, it's just give an error output.

So what we want is to show `no go packages found` error when `go test ./...` don't give any output.

2020-10-24 12:29 UTC, creekorful commented on internal/build/build.go
> +	if len(output) == 0 {
You're totally right, my bad!

2020-10-24 17:18 UTC, creekorful reviewed
LGMTE, however, I would prefer let @Johannestegner take a look at this and let him approve + merge!

2020-10-24 19:01 UTC, Johannestegner approved these changes
LGTM :)

2020-10-24 19:02 UTC, merged